### ISSUE TITLE
Pub/Sub Example

### ISSUE THREAD

**Issue by ljfreelancer88** [bizley/mercure-behavior#2]
Hi,  can you provide an example using pub/sub scenario.  Thank You in advance.
One more question is, do I need to use the behavior method to implement the "publishing"?

**Comment by bizley** [comment]
Hi. You can find examples of using Mercure at https://github.com/bizley/yii2-mercure/blob/master/README.md 
And you don't need to use this behavior exactly, it just provides implementation to make things easier. Take a look at the https://mercure.rocks/ to get more details about Mercure

**Comment by ljfreelancer88** [comment]
Awesome! Thank You.
